#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/config/log

# install app
[[ ! -d /app/watcher/.git ]] && \
	git clone https://github.com/nosmokingbandit/watcher /app/watcher

# permissions
chown -R abc:abc \
	/app \
	/config


